#!/usr/bin/python3

#G.a.R.I
#Grade.
#a.
#Robot.
#Intenigence.
#run "pip install notify2" if notify2 is not installed
#you might need to install espeak-ng https://github.com/espeak-ng/espeak-ng

def clock():
    time.sleep(3600)

import os
import notify2
import time
USE=os.getlogin()
notify2.init("")

while True:
    RED2=open(f"/home/{USE}/reminder.txt", "r").read()
    NOT=notify2.Notification("G.a.R.I", f"Remember to: {RED2}", "/home/chiefchen/Documents/discord-pngs/gun.png")
    NOT.show()
    RED=open(f"/home/{USE}/reminder.txt", "r")
    WORD=RED.read().replace(" ", "_")
    os.system(f"espeak-ng Remember_to_{WORD}.")
    RED.close
    clock()
